version: '3.1'

services:
  db:
    container_name: db_postgres
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./init_database.sql:/init_database.sql
      - ./src/:/src
      - data:/var/lib/postgresql/data

volumes:
  data: