services:
  db:
    container_name: db_postgres
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=db_ratp_sncf  # <- Ajout explicite pour éviter l'erreur de connexion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB"]
      interval: 5s
      retries: 5

volumes:
  postgres_data: